name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gatsby-for-percy:
    name: Percy screenshots via Gatsby build
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      PERCY_TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - run: npm ci
      - run: npx gatsby build
